---
- name: Health Check Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Health Check 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_health:
          title: "Health Check"
          playbook: "playbooks/openshift-checks/pre-install.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

